// Code generated by Kitex v0.0.1. DO NOT EDIT.

package pastercoreservice

import (
	"context"
	"github.com/ameidance/paster_core/model/dto/kitex_gen/ameidance/paster/core"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetPost(ctx context.Context, req *core.GetPostRequest, callOptions ...callopt.Option) (r *core.GetPostResponse, err error)
	SavePost(ctx context.Context, req *core.SavePostRequest, callOptions ...callopt.Option) (r *core.SavePostResponse, err error)
	DeletePost(ctx context.Context, req *core.DeletePostRequest, callOptions ...callopt.Option) (r *core.DeletePostResponse, err error)
	GetComments(ctx context.Context, req *core.GetCommentsRequest, callOptions ...callopt.Option) (r *core.GetCommentsResponse, err error)
	SaveComment(ctx context.Context, req *core.SaveCommentRequest, callOptions ...callopt.Option) (r *core.SaveCommentResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPasterCoreServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPasterCoreServiceClient struct {
	*kClient
}

func (p *kPasterCoreServiceClient) GetPost(ctx context.Context, req *core.GetPostRequest, callOptions ...callopt.Option) (r *core.GetPostResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPost(ctx, req)
}

func (p *kPasterCoreServiceClient) SavePost(ctx context.Context, req *core.SavePostRequest, callOptions ...callopt.Option) (r *core.SavePostResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SavePost(ctx, req)
}

func (p *kPasterCoreServiceClient) DeletePost(ctx context.Context, req *core.DeletePostRequest, callOptions ...callopt.Option) (r *core.DeletePostResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeletePost(ctx, req)
}

func (p *kPasterCoreServiceClient) GetComments(ctx context.Context, req *core.GetCommentsRequest, callOptions ...callopt.Option) (r *core.GetCommentsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetComments(ctx, req)
}

func (p *kPasterCoreServiceClient) SaveComment(ctx context.Context, req *core.SaveCommentRequest, callOptions ...callopt.Option) (r *core.SaveCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SaveComment(ctx, req)
}
