// Code generated by Kitex v0.0.4. DO NOT EDIT.
package core

import (
	"github.com/ameidance/paster_core/model/dto/kitex_gen/paster/core"
	"github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler core.Core, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
